version: "3"

services:
  api_server:
    image: rustlang/rust:nightly
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      DATABASE_URL: db.sqlite
    tty: true
    working_dir: /usr/src/app/
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    command: cargo run
